# Generated by Django 6.0.1 on 2026-01-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro €'), ('USD', 'Dollar $'), ('GBP', 'Livre £'), ('XAF', 'Franc CFA (CEMAC)'), ('XOF', 'Franc CFA (UEMOA)'), ('MAD', 'Dirham Marocain'), ('DZD', 'Dinar Algérien'), ('TND', 'Dinar Tunisien'), ('TRY', 'Lira Turque')], default='XAF', max_length=3),
        ),
        migrations.AddField(
            model_name='agency',
            name='language',
            field=models.CharField(choices=[('FR', 'Français'), ('EN', 'English')], default='FR', max_length=2),
        ),
    ]
