# Generated by Django 6.0.1 on 2026-01-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_currency_agency_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro €'), ('USD', 'Dollar $'), ('GBP', 'Livre £'), ('TRY', 'Lira Turque'), ('XAF', 'Franc CFA (CEMAC)'), ('XOF', 'Franc CFA (UEMOA)'), ('MAD', 'Dirham Marocain'), ('DZD', 'Dinar Algérien'), ('TND', 'Dinar Tunisien')], default='XAF', max_length=3),
        ),
    ]
