# Generated by Django 6.0.1 on 2026-01-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='billing_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-yearly'), ('YEARLY', 'Yearly')], max_length=20),
        ),
    ]
